// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const createBook = `-- name: CreateBook :one
INSERT INTO groups (owner_id, name)
VALUES ($1, $2)
RETURNING id, owner_id, name, created_at
`

type CreateBookParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Group, error) {
	row := q.db.QueryRow(ctx, createBook, arg.OwnerID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, owner_id, name, created_at FROM groups
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getBookByOwnerAndName = `-- name: GetBookByOwnerAndName :one
SELECT id, owner_id, name, created_at FROM groups
WHERE owner_id = $1 AND name = $2
`

type GetBookByOwnerAndNameParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) GetBookByOwnerAndName(ctx context.Context, arg GetBookByOwnerAndNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, getBookByOwnerAndName, arg.OwnerID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_id, user_id, role, created_at FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listBooksByUser = `-- name: ListBooksByUser :many
SELECT g.id, g.owner_id, g.name, g.created_at, gm.role
FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY g.name
`

type ListBooksByUserRow struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	Role      string    `json:"role"`
}

func (q *Queries) ListBooksByUser(ctx context.Context, userID uuid.UUID) ([]ListBooksByUserRow, error) {
	rows, err := q.db.Query(ctx, listBooksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksByUserRow{}
	for rows.Next() {
		var i ListBooksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2 AND role != 'owner'
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const setActiveBook = `-- name: SetActiveBook :exec
UPDATE profiles
SET active_book_id = $2
WHERE id = $1
`

type SetActiveBookParams struct {
	ID           uuid.UUID   `json:"id"`
	ActiveBookID pgtype.UUID `json:"active_book_id"`
}

func (q *Queries) SetActiveBook(ctx context.Context, arg SetActiveBookParams) error {
	_, err := q.db.Exec(ctx, setActiveBook, arg.ID, arg.ActiveBookID)
	return err
}
