// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_tokens.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginToken = `-- name: CreateLoginToken :exec
INSERT INTO login_tokens (token, telegram_id, telegram_username, display_name, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLoginTokenParams struct {
	Token            string      `json:"token"`
	TelegramID       int64       `json:"telegram_id"`
	TelegramUsername pgtype.Text `json:"telegram_username"`
	DisplayName      pgtype.Text `json:"display_name"`
	ExpiresAt        time.Time   `json:"expires_at"`
}

func (q *Queries) CreateLoginToken(ctx context.Context, arg CreateLoginTokenParams) error {
	_, err := q.db.Exec(ctx, createLoginToken,
		arg.Token,
		arg.TelegramID,
		arg.TelegramUsername,
		arg.DisplayName,
		arg.ExpiresAt,
	)
	return err
}
