// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type GroupMember struct {
	GroupID   uuid.UUID `json:"group_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type LoginToken struct {
	Token            string             `json:"token"`
	TelegramID       int64              `json:"telegram_id"`
	TelegramUsername pgtype.Text        `json:"telegram_username"`
	DisplayName      pgtype.Text        `json:"display_name"`
	CreatedAt        time.Time          `json:"created_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
}

type Profile struct {
	ID               uuid.UUID   `json:"id"`
	TelegramID       pgtype.Int8 `json:"telegram_id"`
	DisplayName      pgtype.Text `json:"display_name"`
	CreatedAt        time.Time   `json:"created_at"`
	TelegramUsername pgtype.Text `json:"telegram_username"`
	ActiveBookID     pgtype.UUID `json:"active_book_id"`
}

type Transaction struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	Amount      float64     `json:"amount"`
	Type        string      `json:"type"`
	Category    string      `json:"category"`
	Description pgtype.Text `json:"description"`
	OccurredAt  time.Time   `json:"occurred_at"`
	CreatedAt   time.Time   `json:"created_at"`
	GroupID     pgtype.UUID `json:"group_id"`
}
