// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LoginToken struct {
	Token            string             `json:"token"`
	TelegramID       int64              `json:"telegram_id"`
	TelegramUsername pgtype.Text        `json:"telegram_username"`
	DisplayName      pgtype.Text        `json:"display_name"`
	CreatedAt        time.Time          `json:"created_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
}

type Profile struct {
	ID               uuid.UUID   `json:"id"`
	TelegramID       pgtype.Int8 `json:"telegram_id"`
	DisplayName      pgtype.Text `json:"display_name"`
	CreatedAt        time.Time   `json:"created_at"`
	TelegramUsername pgtype.Text `json:"telegram_username"`
}

type RecurringRule struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	Amount       float64     `json:"amount"`
	Type         string      `json:"type"`
	Category     string      `json:"category"`
	Description  pgtype.Text `json:"description"`
	Frequency    string      `json:"frequency"`
	DayOfMonth   pgtype.Int4 `json:"day_of_month"`
	MonthOfYear  pgtype.Int4 `json:"month_of_year"`
	DayOfWeek    pgtype.Int4 `json:"day_of_week"`
	Active       bool        `json:"active"`
	LastPostedOn pgtype.Date `json:"last_posted_on"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Transaction struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	Amount          float64     `json:"amount"`
	Type            string      `json:"type"`
	Category        string      `json:"category"`
	Description     pgtype.Text `json:"description"`
	OccurredAt      time.Time   `json:"occurred_at"`
	CreatedAt       time.Time   `json:"created_at"`
	RecurringRuleID pgtype.UUID `json:"recurring_rule_id"`
}
