// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileByTelegramID = `-- name: GetProfileByTelegramID :one
SELECT id, telegram_id, display_name, created_at, telegram_username, active_book_id FROM profiles
WHERE telegram_id = $1
`

func (q *Queries) GetProfileByTelegramID(ctx context.Context, telegramID pgtype.Int8) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByTelegramID, telegramID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.TelegramUsername,
		&i.ActiveBookID,
	)
	return i, err
}

const getProfileByTelegramUsername = `-- name: GetProfileByTelegramUsername :one
SELECT id, telegram_id, display_name, created_at, telegram_username, active_book_id FROM profiles
WHERE telegram_username = $1
`

func (q *Queries) GetProfileByTelegramUsername(ctx context.Context, telegramUsername pgtype.Text) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByTelegramUsername, telegramUsername)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.TelegramUsername,
		&i.ActiveBookID,
	)
	return i, err
}
