// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_rules.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringRule = `-- name: CreateRecurringRule :one
INSERT INTO recurring_rules (
    user_id, amount, type, category, description,
    frequency, day_of_month, month_of_year, day_of_week
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, amount, type, category, description, frequency, day_of_month, month_of_year, day_of_week, active, last_posted_on, created_at
`

type CreateRecurringRuleParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Amount      float64     `json:"amount"`
	Type        string      `json:"type"`
	Category    string      `json:"category"`
	Description pgtype.Text `json:"description"`
	Frequency   string      `json:"frequency"`
	DayOfMonth  pgtype.Int4 `json:"day_of_month"`
	MonthOfYear pgtype.Int4 `json:"month_of_year"`
	DayOfWeek   pgtype.Int4 `json:"day_of_week"`
}

func (q *Queries) CreateRecurringRule(ctx context.Context, arg CreateRecurringRuleParams) (RecurringRule, error) {
	row := q.db.QueryRow(ctx, createRecurringRule,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Category,
		arg.Description,
		arg.Frequency,
		arg.DayOfMonth,
		arg.MonthOfYear,
		arg.DayOfWeek,
	)
	var i RecurringRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.Category,
		&i.Description,
		&i.Frequency,
		&i.DayOfMonth,
		&i.MonthOfYear,
		&i.DayOfWeek,
		&i.Active,
		&i.LastPostedOn,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecurringRule = `-- name: DeleteRecurringRule :execrows
DELETE FROM recurring_rules
WHERE id = $1 AND user_id = $2
`

type DeleteRecurringRuleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRecurringRule(ctx context.Context, arg DeleteRecurringRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecurringRule, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRecurringRulesByUser = `-- name: ListRecurringRulesByUser :many
SELECT id, user_id, amount, type, category, description, frequency, day_of_month, month_of_year, day_of_week, active, last_posted_on, created_at FROM recurring_rules
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListRecurringRulesByUser(ctx context.Context, userID uuid.UUID) ([]RecurringRule, error) {
	rows, err := q.db.Query(ctx, listRecurringRulesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringRule{}
	for rows.Next() {
		var i RecurringRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.Description,
			&i.Frequency,
			&i.DayOfMonth,
			&i.MonthOfYear,
			&i.DayOfWeek,
			&i.Active,
			&i.LastPostedOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
