// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, amount, type, category, description, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, amount, type, category, description, occurred_at, created_at, recurring_rule_id
`

type CreateTransactionParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Amount      float64     `json:"amount"`
	Type        string      `json:"type"`
	Category    string      `json:"category"`
	Description pgtype.Text `json:"description"`
	OccurredAt  time.Time   `json:"occurred_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Category,
		arg.Description,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.Category,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.RecurringRuleID,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, amount, type, category, description, occurred_at, created_at, recurring_rule_id FROM transactions
ORDER BY occurred_at DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.RecurringRuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, amount, type, category, description, occurred_at, created_at, recurring_rule_id FROM transactions
WHERE user_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.RecurringRuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
